### ISSUE TITLE
Multiply Overflow in Fingerprint

### ISSUE THREAD

**Issue by 0mbi** [DCSO/bloom#14]
# The Issue: 
https://github.com/DCSO/bloom/blob/691ea61436538672245309cca71590722558dd47/bloom.go#L201 
produces the an multiply overflow.

```
	for i := uint64(0); i < s.k; i++ {
		hn = (hn * g) % m
		fingerprint[i] = uint64(hn % s.m)
	}
```
hn * g overflows in the unit tests. I am not sure if this is really an issue or if this behaviour is intended.

# To reproduce:
Add a overflow check function like (as taken
from https://www.programming-idioms.org/idiom/86/check-if-integer-multiplication-will-overflow)
```
func multiplyWillOverflow(x, y uint64) bool {
   if x <= 1 || y <= 1 {
     return false
   }
   d := x * y
   return d/y != x
}
```
Add the following after 
`hn = (hn * g) %m`:
```
if multiplyWillOverflow(hn, g) {
  panic("Multiply overflow occured")
}
```
And run `go test ./..`

**Comment by satta** [comment]
AFAICS this is observed correctly, but should not make a difference here as long as integer sizes are fixed (e.g. between architectures). Even with an overflow happening, fingerprint calculation is still deterministic and the distribution properties of the hash values (and hence bits) should also remain unchanged. @adewes any comments on that?

**Comment by adewes** [comment]
Howdie @satta & @0mbi :D I checked it back when I implemented it but found that it didn't change the collission probability so I left it (as otherwise we'd need to use a modular arithmetic library or implement our own, which would make the whole thing much slower). In the Python version (which supports big integers out of the box) we also truncate the multiplication result before performing the modulo, so it's compatible to the Golang version (https://github.com/DCSO/flor/blob/master/flor/filter.py#L113).

**Comment by 0mbi** [comment]
Very well, nice that things work as expected :-)

I guess that's a close then.

**Comment by satta** [comment]
Thanks for being vigilant anyway :)
